# Generated by Django 3.1.7 on 2021-03-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_test', '0003_auto_20210301_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(),
        ),
    ]
