# Generated by Django 3.1.7 on 2021-03-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_test', '0004_auto_20210301_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
