# Generated by Django 3.1.7 on 2021-03-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_test', '0006_auto_20210301_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sortpos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=255)),
                ('ttext', models.TextField()),
            ],
        ),
    ]
