# Generated by Django 3.1.7 on 2021-03-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_test', '0008_categoriesmptt'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriesmptt',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
